# Generated by Django 6.0.6 on 2026-06-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nazione', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Autori',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=400)),
                ('anno', models.IntegerField()),
                ('genere', models.CharField(max_length=100)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.autore')),
            ],
            options={
                'verbose_name_plural': 'Libri',
            },
        ),
    ]
