# Generated by Django 6.0.5 on 2026-06-24 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scarpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('valuta', models.CharField(default='EUR', max_length=10)),
                ('descrizione', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('materiale', models.CharField(max_length=200)),
                ('disponibilita', models.BooleanField(default=True)),
                ('taglie_disponibili', models.JSONField(default=list, help_text='Lista di taglie disponibili, es: [36, 37, 38, 39, 40]')),
                ('immagine_url', models.URLField(blank=True, help_text="URL dell'immagine del prodotto (es: https://picsum.photos/seed/oxford/400/400)", max_length=500, null=True)),
                ('sconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
